import { ThemeId, ThemeDefinition, Menu } from './types';

export const themeDefinitions: ThemeDefinition[] = [
  {
    id: 'fun',
    name: 'Fun & Playful',
    description: 'Burger joints, taco trucks, brunch spots',
    emoji: '🎉',
    colors: {
      primary: '#D45A20',
      bg: '#FFFBF5',
      surface: '#FFFFFF',
      surfaceHover: '#FFF5EB',
      text: '#1A1A1A',
      textSecondary: '#5C5C5C',
      textMuted: '#B8A898',
      accent: '#FF6B35',
      accentHover: '#E55A25',
      accentText: '#FFFFFF',
      border: '#F0E6D8',
      borderSubtle: '#F7F0E8',
      badge: '#FFF0E8',
      badgeText: '#FF6B35',
    },
    fonts: {
      heading: "'Trebuchet MS', 'Gill Sans', sans-serif",
      body: "system-ui, -apple-system, 'Segoe UI', sans-serif",
    },
    radius: { sm: '8px', md: '12px', lg: '20px', pill: '9999px' },
    shadows: {
      sm: '0 1px 3px rgba(160,120,80,0.08)',
      md: '0 4px 12px rgba(160,120,80,0.10)',
      lg: '0 12px 24px rgba(160,120,80,0.14)',
    },
    backgroundPattern: 'dots',
    borderRadius: 'lg',
  },
  {
    id: 'classy',
    name: 'Classy & Refined',
    description: 'Steakhouses, wine bars, upscale lounges',
    emoji: '🍷',
    colors: {
      primary: '#5A1010',
      bg: '#FAF9F5',
      surface: '#FFFFFF',
      surfaceHover: '#F5F3ED',
      text: '#1C1917',
      textSecondary: '#57534E',
      textMuted: '#A8A29E',
      accent: '#7F1D1D',
      accentHover: '#6B1717',
      accentText: '#FFFFFF',
      border: '#E7E5E4',
      borderSubtle: '#F0EDEA',
      badge: '#FEF2F2',
      badgeText: '#7F1D1D',
    },
    fonts: {
      heading: "Georgia, 'Times New Roman', serif",
      body: "system-ui, -apple-system, 'Segoe UI', sans-serif",
    },
    radius: { sm: '4px', md: '6px', lg: '10px', pill: '9999px' },
    shadows: {
      sm: '0 1px 2px rgba(28,25,23,0.05)',
      md: '0 4px 8px rgba(28,25,23,0.07)',
      lg: '0 10px 20px rgba(28,25,23,0.10)',
    },
    backgroundPattern: 'none',
    borderRadius: 'sm',
  },
  {
    id: 'funky',
    name: 'Funky & Bold',
    description: 'Fusion kitchens, cocktail bars, pop-ups',
    emoji: '⚡',
    colors: {
      primary: '#1A1230',
      bg: '#0F0A1A',
      surface: '#1A1230',
      surfaceHover: '#231A40',
      text: '#F5F0FF',
      textSecondary: '#C4B8E0',
      textMuted: '#7B6A9E',
      accent: '#E040FB',
      accentHover: '#C830E0',
      accentText: '#FFFFFF',
      border: '#2D2450',
      borderSubtle: '#1E1840',
      badge: '#2A1840',
      badgeText: '#E040FB',
    },
    fonts: {
      heading: "'Impact', 'Arial Black', sans-serif",
      body: "system-ui, -apple-system, 'Segoe UI', sans-serif",
    },
    radius: { sm: '4px', md: '8px', lg: '14px', pill: '9999px' },
    shadows: {
      sm: '0 1px 3px rgba(0,0,0,0.3)',
      md: '0 4px 12px rgba(0,0,0,0.4)',
      lg: '0 12px 28px rgba(0,0,0,0.5)',
    },
    backgroundPattern: 'grain',
    borderRadius: 'md',
  },
  {
    id: 'chic',
    name: 'Chic & Minimal',
    description: 'Boutique cafes, concept restaurants',
    emoji: '✦',
    colors: {
      primary: '#111111',
      bg: '#FFFFFF',
      surface: '#FFFFFF',
      surfaceHover: '#F5F5F5',
      text: '#111111',
      textSecondary: '#555555',
      textMuted: '#AAAAAA',
      accent: '#111111',
      accentHover: '#333333',
      accentText: '#FFFFFF',
      border: '#EBEBEB',
      borderSubtle: '#F5F5F5',
      badge: '#F5F5F5',
      badgeText: '#111111',
    },
    fonts: {
      heading: "Georgia, 'Palatino Linotype', serif",
      body: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    },
    radius: { sm: '2px', md: '4px', lg: '8px', pill: '9999px' },
    shadows: {
      sm: '0 0 0 1px rgba(0,0,0,0.06)',
      md: '0 0 0 1px rgba(0,0,0,0.06), 0 3px 8px rgba(0,0,0,0.04)',
      lg: '0 0 0 1px rgba(0,0,0,0.06), 0 8px 20px rgba(0,0,0,0.06)',
    },
    backgroundPattern: 'none',
    borderRadius: 'sm',
  },
  {
    id: 'classic-theme',
    name: 'Classic & Timeless',
    description: 'French bistros, trattorias, family spots',
    emoji: '🏛',
    colors: {
      primary: '#6B4F10',
      bg: '#F8F5EE',
      surface: '#FFFDF7',
      surfaceHover: '#F3EFE5',
      text: '#2C2416',
      textSecondary: '#6B5D4A',
      textMuted: '#A69880',
      accent: '#8B6914',
      accentHover: '#755810',
      accentText: '#FFFFFF',
      border: '#E5DFD0',
      borderSubtle: '#EDE8DC',
      badge: '#FDF8ED',
      badgeText: '#8B6914',
    },
    fonts: {
      heading: "Georgia, 'Palatino Linotype', 'Book Antiqua', serif",
      body: "Georgia, 'Times New Roman', serif",
    },
    radius: { sm: '2px', md: '4px', lg: '8px', pill: '9999px' },
    shadows: {
      sm: '0 1px 2px rgba(44,36,22,0.06)',
      md: '0 3px 8px rgba(44,36,22,0.08)',
      lg: '0 8px 20px rgba(44,36,22,0.10)',
    },
    backgroundPattern: 'none',
    borderRadius: 'sm',
  },
  {
    id: 'finedining',
    name: 'Fine Dining',
    description: 'Michelin-starred, tasting menus, omakase',
    emoji: '🥂',
    colors: {
      primary: '#161616',
      bg: '#0C0C0C',
      surface: '#161616',
      surfaceHover: '#1E1E1E',
      text: '#F0ECE2',
      textSecondary: '#B8B0A0',
      textMuted: '#6B6358',
      accent: '#C9A84C',
      accentHover: '#B89840',
      accentText: '#0C0C0C',
      border: '#282420',
      borderSubtle: '#1E1A16',
      badge: '#1E1A10',
      badgeText: '#C9A84C',
    },
    fonts: {
      heading: "'Palatino Linotype', 'Book Antiqua', Palatino, serif",
      body: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    },
    radius: { sm: '2px', md: '4px', lg: '8px', pill: '9999px' },
    shadows: {
      sm: '0 1px 3px rgba(0,0,0,0.4)',
      md: '0 4px 12px rgba(0,0,0,0.5)',
      lg: '0 12px 30px rgba(0,0,0,0.6)',
    },
    backgroundPattern: 'none',
    borderRadius: 'sm',
  },
  {
    id: 'asian',
    name: 'Modern Asian',
    description: 'Ramen bars, izakayas, dim sum, pho',
    emoji: '🥢',
    colors: {
      primary: '#8C1A18',
      bg: '#FAFAF8',
      surface: '#FFFFFF',
      surfaceHover: '#F5F5F0',
      text: '#1A1A18',
      textSecondary: '#5A5A55',
      textMuted: '#9C9C95',
      accent: '#D1342F',
      accentHover: '#B82A26',
      accentText: '#FFFFFF',
      border: '#E8E8E0',
      borderSubtle: '#F0F0EA',
      badge: '#FFF1F0',
      badgeText: '#D1342F',
    },
    fonts: {
      heading: "'Trebuchet MS', 'Gill Sans', sans-serif",
      body: "system-ui, -apple-system, 'Segoe UI', sans-serif",
    },
    radius: { sm: '4px', md: '6px', lg: '12px', pill: '9999px' },
    shadows: {
      sm: '0 1px 2px rgba(26,26,24,0.06)',
      md: '0 4px 8px rgba(26,26,24,0.08)',
      lg: '0 10px 20px rgba(26,26,24,0.12)',
    },
    backgroundPattern: 'lines',
    borderRadius: 'sm',
  },
  {
    id: 'tapas',
    name: 'Tapas & Wine',
    description: 'Spanish tapas, mezze bars, shared plates',
    emoji: '🫒',
    colors: {
      primary: '#6B3218',
      bg: '#FBF8F4',
      surface: '#FFFFFF',
      surfaceHover: '#F7F2EA',
      text: '#2D1F12',
      textSecondary: '#6B5540',
      textMuted: '#B09878',
      accent: '#A0522D',
      accentHover: '#8B4525',
      accentText: '#FFFFFF',
      border: '#E8DFD0',
      borderSubtle: '#F0E8DC',
      badge: '#FDF5EC',
      badgeText: '#A0522D',
    },
    fonts: {
      heading: "Georgia, 'Times New Roman', serif",
      body: "system-ui, -apple-system, 'Segoe UI', sans-serif",
    },
    radius: { sm: '4px', md: '8px', lg: '14px', pill: '9999px' },
    shadows: {
      sm: '0 1px 3px rgba(45,31,18,0.06)',
      md: '0 4px 10px rgba(45,31,18,0.08)',
      lg: '0 10px 24px rgba(45,31,18,0.12)',
    },
    backgroundPattern: 'dots',
    borderRadius: 'md',
  },
  {
    id: 'coastal',
    name: 'Coastal Fresh',
    description: 'Seafood shacks, poke bars, waterfront',
    emoji: '🌊',
    colors: {
      primary: '#005A8C',
      bg: '#F7FBFC',
      surface: '#FFFFFF',
      surfaceHover: '#EDF5F8',
      text: '#0F2B3C',
      textSecondary: '#3D6070',
      textMuted: '#8BAAB8',
      accent: '#0077B6',
      accentHover: '#00669E',
      accentText: '#FFFFFF',
      border: '#D4E8F0',
      borderSubtle: '#E4F0F5',
      badge: '#E8F4FA',
      badgeText: '#0077B6',
    },
    fonts: {
      heading: "'Trebuchet MS', 'Gill Sans', sans-serif",
      body: "system-ui, -apple-system, 'Segoe UI', sans-serif",
    },
    radius: { sm: '6px', md: '10px', lg: '16px', pill: '9999px' },
    shadows: {
      sm: '0 1px 3px rgba(15,43,60,0.06)',
      md: '0 4px 10px rgba(15,43,60,0.08)',
      lg: '0 10px 24px rgba(15,43,60,0.12)',
    },
    backgroundPattern: 'waves',
    borderRadius: 'md',
  },
  {
    id: 'garden',
    name: 'Farm & Garden',
    description: 'Farm-to-table, vegetarian, organic cafes',
    emoji: '🌿',
    colors: {
      primary: '#1E4A14',
      bg: '#F6F9F4',
      surface: '#FFFFFF',
      surfaceHover: '#EFF5EB',
      text: '#1A2E12',
      textSecondary: '#4A6040',
      textMuted: '#8DAA80',
      accent: '#2D6A1E',
      accentHover: '#245818',
      accentText: '#FFFFFF',
      border: '#D8E8D0',
      borderSubtle: '#E6F0E0',
      badge: '#EBF5E6',
      badgeText: '#2D6A1E',
    },
    fonts: {
      heading: "Georgia, 'Palatino Linotype', serif",
      body: "system-ui, -apple-system, 'Segoe UI', sans-serif",
    },
    radius: { sm: '4px', md: '8px', lg: '14px', pill: '9999px' },
    shadows: {
      sm: '0 1px 3px rgba(26,46,18,0.06)',
      md: '0 4px 10px rgba(26,46,18,0.08)',
      lg: '0 10px 24px rgba(26,46,18,0.12)',
    },
    backgroundPattern: 'none',
    borderRadius: 'md',
  },
];

export function getThemeById(id: ThemeId): ThemeDefinition | undefined {
  return themeDefinitions.find((t) => t.id === id);
}

export function themeToDesignFields(theme: ThemeDefinition): Partial<Menu['design']> {
  return {
    primaryColor: theme.colors.primary,
    accentColor: theme.colors.accent,
    backgroundColor: theme.colors.bg,
    textColor: theme.colors.text,
    headingFont: theme.fonts.heading,
    bodyFont: theme.fonts.body,
    backgroundPattern: theme.backgroundPattern,
    borderRadius: theme.borderRadius,
    themeId: theme.id,
  };
}
